### ISSUE TITLE
Change currency (USD)

### ISSUE THREAD

**Issue by RedPlumpTomato** [JM1F/Cryptocurrency-Widget#3]
Please include an option to change native currency (price column). Thanks.

**Comment by JM1F** [comment]
What do you mean by this? There is already a currency change feature in the bottom left. Would you like it to automatically change on start-up?

**Comment by RedPlumpTomato** [comment]
Ah!  I didn’t notice it. Thanks
________________________________

**Comment by JM1F** [comment]
No worries, I only added three currencies when testing but more can be added if need be :)
