### ISSUE TITLE
Add total coins

### ISSUE THREAD

**Issue by hendrikbez** [JM1F/Cryptocurrency-Widget#4]
Thank you for this widget.
1. Is it possible to add the amount of coins you have for each token, then show the price for it. (say price is 0.1 per token and you put in 
    10 tokens, then it must show price of 1.0, and it must save it.
3. Can you make it so we can add our tokens, and delete the ones we do not use.
4. Can you add ZAR as currency
5. If possible can you show two currency's at one

**Comment by JM1F** [comment]
Thanks for your recommendations and improvements @hendrikbez,

1. This is a great idea and may influence future development. Despite this, it will take a while to implement, so it may take a while to come to fruition.

2. This is also another feature in the pipeline for future releases.

3. If you give me extra details about the ZAR currency, I will add it to the next release of the widget.

4. This will be added into the next release of the widget.

If you have any other questions or issues, please do not hesitate to contact me. 👍

**Comment by hendrikbez** [comment]
Hi
Thank you for replying to me.

The ZAR is the currency of South Africa

Hendrik

**Comment by JM1F** [comment]
Ok, no worries, I will implement it within the next release.
